language: c
matrix:
  include:
    - os: linux
      env: TARGET_MACHINE=i3le
    - os: linux
      env: TARGET_MACHINE=ti3le
dist: trusty
addons:
  apt:
    packages:
      - gcc-multilib
      - lib32ncurses5-dev
      - libx32ncurses5-dev
script:
  - .travis/dobuild.sh
